# Constrained Optimization

In [ ]:
def MONTHLY_RETURN( SYMBOLS , FROM , TO ) :
  from yfinance import download
  DATA = download( tickers=SYMBOLS , start=FROM , end=TO )
  ADJUSTED = DATA["Adj Close"]
  return ADJUSTED.resample( rule="M" ).last().pct_change().dropna()

EGGS = MONTHLY_RETURN(SYMBOLS=["AAPL","UAL","GLD","SBUX", "TSLA" ] , FROM="2018-12-31" , TO="2024-01-1")
EGGS.head()

[*********************100%%**********************]  5 of 5 completed


Ticker          AAPL       GLD      SBUX      TSLA       UAL
Date                                                        
2019-01-31  0.055154  0.028866  0.058074 -0.077464  0.042279
2019-02-28  0.044776 -0.006092  0.036494  0.041886  0.006188
2019-03-31  0.097026 -0.015969  0.058070 -0.125109 -0.091447
2019-04-30  0.056436 -0.006639  0.044929 -0.147109  0.113813
2019-05-31 -0.124213  0.017574 -0.016312 -0.224266 -0.126153

In [ ]:
!pip install Riskfolio-Lib
import riskfolio as rf

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.0/301.0 kB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 17.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 40.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 27.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 22.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.0/983.0 kB 26.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.9/159.9 kB 7.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.0/235.0 kB 4.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 14.2 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstallin

In [ ]:
OBJECT = rf.Portfolio(returns=EGGS)
OBJECT.assets_stats()
SAFEST = OBJECT.optimization(rm="MV" , obj="MinRisk", rf=0.0015)
round( SAFEST , 4 )

weights
AAPL   0.0210
GLD    0.8415
SBUX   0.0436
TSLA   0.0000
UAL    0.0938

In [ ]:
from numpy import *


# **Constraint for All Assets**

In [ ]:
A_BOTTOM = identity(n=5) * (-1)
A_BOTTOM

array([[-1., -0., -0., -0., -0.],
       [-0., -1., -0., -0., -0.],
       [-0., -0., -1., -0., -0.],
       [-0., -0., -0., -1., -0.],
       [-0., -0., -0., -0., -1.]])

In [ ]:
B_BOTTOM = full(shape=[5,1], fill_value=-0.35)
B_BOTTOM

array([[-0.35],
       [-0.35],
       [-0.35],
       [-0.35],
       [-0.35]])

In [ ]:
OBJECT = rf.Portfolio(returns=EGGS, ainequality= A_BOTTOM, binequality=B_BOTTOM, sht=True)
OBJECT.upperlng = 1.2
OBJECT.assets_stats()
SAFEST = OBJECT.optimization(rm="MV" , obj="MinRisk")
print(round(SAFEST,7))
print("    ")
print(round(SAFEST,7)* 100)

       weights
AAPL  0.350000
GLD   0.350000
SBUX  0.296413
TSLA -0.076906
UAL   0.080492
    
       weights
AAPL  35.00000
GLD   35.00000
SBUX  29.64134
TSLA  -7.69057
UAL    8.04923


In [ ]:
 0.080492 * 30000


2414.7599999999998

In [ ]:
EGGS = MONTHLY_RETURN(SYMBOLS=["AAPL","DAL","GLD","SBUX", "TSLA" ] , FROM="2018-12-31" , TO="2024-01-1")
EGGS.head()

[*********************100%%**********************]  5 of 5 completed


Ticker          AAPL       DAL       GLD      SBUX      TSLA
Date                                                        
2019-01-31  0.055154 -0.009419  0.028866  0.058074 -0.077464
2019-02-28  0.044776  0.010045 -0.006092  0.036494  0.041886
2019-03-31  0.097026  0.041751 -0.015969  0.058070 -0.125109
2019-04-30  0.056436  0.128558 -0.006639  0.044929 -0.147109
2019-05-31 -0.124213 -0.111150  0.017574 -0.016312 -0.224266

In [ ]:

a = array(object=[[-1,-1,0,0,0]])
a

array([[-1, -1,  0,  0,  0]])

In [ ]:
b = array(object=[[-0.6]])
b

array([[-0.6]])

In [ ]:
OBJECT = rf.Portfolio(returns=EGGS, ainequality= a, binequality=b, sht=True)
OBJECT.upperlng = 1.2
OBJECT.assets_stats()
SAFEST = OBJECT.optimization(rm="MV" , obj="Sharpe", rf=0.0015)
print(round(SAFEST,7))
print("    ")
print(round(SAFEST,7)* 100)

       weights
AAPL  0.798768
DAL  -0.198768
GLD   0.315054
SBUX -0.001231
TSLA  0.086178
    
       weights
AAPL  79.87678
DAL  -19.87681
GLD   31.50536
SBUX  -0.12310
TSLA   8.61777


In [ ]:
-0.198768 * 25000

-4969.2

# **Question 7 MidTerm**

In [ ]:
EGGS = MONTHLY_RETURN(SYMBOLS=["CMG","TSLA","CAKE","SPOT"] , FROM="2019-01-31" , TO="2024-02-01")
print(EGGS.head())
print(" ")
a = array(object=[[-1,0,-1,0]])
a
print("a ")
print(a)
print(" ")

b = array(object=[[-0.7]])
b

print("b ")
print(b)
print(" ")

OBJECT = rf.Portfolio(returns=EGGS, ainequality= a, binequality=b, sht=True)
OBJECT.upperlng = 1.5
OBJECT.assets_stats()
SAFEST = OBJECT.optimization(rm="MV" , obj="MinRisk")


print(round(SAFEST,7))
print("    ")
print(round(SAFEST,7)* 100)

[*********************100%%**********************]  4 of 4 completed


Ticker          CAKE       CMG      SPOT      TSLA
Date                                              
2019-02-28  0.053922  0.147127  0.034625  0.041886
2019-03-31  0.041516  0.169177 -0.009562 -0.125109
2019-04-30  0.014309 -0.031353 -0.021830 -0.147109
2019-05-31 -0.122314 -0.040797 -0.075053 -0.224266
2019-06-30  0.010867  0.110475  0.164357  0.206848
 
a 
[[-1  0 -1  0]]
 
b 
[[-0.7]]
 
       weights
CAKE  0.262424
CMG   0.631281
SPOT  0.185789
TSLA -0.079494
    
       weights
CAKE  26.24238
CMG   63.12813
SPOT  18.57889
TSLA  -7.94940


In [ ]:
round(0.262424 * 45000)

11809

# **Question 6 MidTerm**

In [ ]:
EGGS = MONTHLY_RETURN(SYMBOLS=["CMG","TSLA","CAKE","SPOT"] , FROM="2019-01-31" , TO="2024-02-01")
EGGS.head()


A_BOTTOM = identity(n=4) * (-1)
A_BOTTOM
print("A Bottom")
print(A_BOTTOM)
print(" ")

B_BOTTOM = full(shape=[4,1], fill_value=-0.7)
B_BOTTOM
print("B Bottom")
print(B_BOTTOM)
print(" ")

OBJECT = rf.Portfolio(returns=EGGS, ainequality= A_BOTTOM, binequality=B_BOTTOM, sht=True)
OBJECT.upperlng = 1.5
OBJECT.assets_stats()
SAFEST = OBJECT.optimization(rm="MV" , obj="Sharpe", rf=0.001)
print(SAFEST)
print("    ")
print(round(SAFEST,7)* 100)

[*********************100%%**********************]  4 of 4 completed


A Bottom
[[-1. -0. -0. -0.]
 [-0. -1. -0. -0.]
 [-0. -0. -1. -0.]
 [-0. -0. -0. -1.]]
 
B Bottom
[[-0.7]
 [-0.7]
 [-0.7]
 [-0.7]]
 
       weights
CAKE -0.145878
CMG   0.700000
SPOT -0.054122
TSLA  0.500000
    
       weights
CAKE -14.58777
CMG   70.00000
SPOT  -5.41222
TSLA  50.00000


In [ ]:
round(-0.145878 * 45000)

-6565

# **Stacking Constraints**
Constraint for all and the previous constraints

In [ ]:
a = vstack(tup=[A,A_BOTTOM])
b = vstack(tup=[B,B_BOTTOM])

NameError: name 'A' is not defined

In [ ]:
a

In [ ]:
b

In [ ]:
OBJECT = rf.Portfolio(returns=EGGS, ainequality=a, binequality=b, sht=True)
OBJECT.upperlng = 1.5
OBJECT.assets_stats()
SAFEST = OBJECT.optimization(rm="MV" , obj="MinRisk", rf=0.15)
round(SAFEST,4)