# Constrained Optimization

In [ ]:
def MONTHLY_RETURN( SYMBOLS , FROM , TO ) :
  from yfinance import download
  DATA = download( tickers=SYMBOLS , start=FROM , end=TO )
  ADJUSTED = DATA["Adj Close"]
  return ADJUSTED.resample( rule="M" ).last().pct_change().dropna()

EGGS = MONTHLY_RETURN(SYMBOLS=["AAPL","DAL","GLD","SBUX"] , FROM="2018-12-31" , TO="2024-01-1")
EGGS.head()

[*********************100%%**********************]  4 of 4 completed


Ticker          AAPL       DAL       GLD      SBUX
Date                                              
2019-01-31  0.055154 -0.009419  0.028866  0.058074
2019-02-28  0.044776  0.010045 -0.006092  0.036494
2019-03-31  0.097026  0.041751 -0.015969  0.058070
2019-04-30  0.056436  0.128558 -0.006639  0.044929
2019-05-31 -0.124213 -0.111150  0.017574 -0.016312

In [ ]:
!pip install Riskfolio-Lib
import riskfolio as rf

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.0/301.0 kB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 78.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 72.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 54.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 86.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.0/983.0 kB 52.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.9/159.9 kB 12.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.7/227.7 kB 25.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 32.1 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstall

In [ ]:
OBJECT = rf.Portfolio(returns=EGGS)
OBJECT.assets_stats()
SAFEST = OBJECT.optimization(rm="MV" , obj="MinRisk", rf=0.15)
round( SAFEST , 4 )

weights
AAPL   0.0043
DAL    0.1256
GLD    0.8497
SBUX   0.0204

In [ ]:
from numpy import *


In [ ]:
A = array(object=[[-1,-1,0,0]])
A

array([[-1, -1,  0,  0]])

In [ ]:
B = array(object=[[-0.6]])
B

array([[-0.6]])

In [ ]:
OBJECT = rf.Portfolio(returns=EGGS, ainequality=A, binequality=B, sht=True)
OBJECT.upperlng = 1.5
OBJECT.assets_stats()
SAFEST = OBJECT.optimization(rm="MV" , obj="MinRisk", rf=0.15)
round(SAFEST,4)

weights
AAPL   0.0043
DAL    0.1256
GLD    0.8497
SBUX   0.0204

# **Return with Investment Amount**

In [ ]:
!pip install empyrial
!pip install pyfolio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 6.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 7.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.3/247.3 kB 12.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 31.9 MB/s eta 0:00:00
  Created wheel for empyrical: filename=empyrical-0.5.5-py3-none-any.whl size=39756 sha256=1910ee4d5131cd61aa62c6e1c8d2a516a144117709bc6662296bb8eaacbe9cea
  Stored in directory: /root/.cache/pip/wheels/0e/2e/f2/d6d2d9a1eb8fbbd9949bb5d4c00f753e3b74e5bd7ed10b1d36
  Created wheel for fpdf: filename=fpdf-1.7.2-py2.py3-none-any.whl size=40702 sha256=5b1c48167bd3f0edb26019dd53b423c72983c59b4258b4536cdda1351f3f093d
  Stored in directory: 

In [ ]:
from empyrial import *
import pyfolio
from plotly.express import *

def GetDailyReturnsWithWeightsAndPortfolio(stocks, weights, startDate, endDate, checkDate, startingValue):
  print("Weights: ", weights)

  DAILY = get_returns(stocks=stocks,
            wts= weights,
            start_date=startDate,
            end_date=endDate)
  DOUGH = pyfolio.timeseries.cum_returns(returns=DAILY, starting_value=startingValue)
  return DOUGH[checkDate]

In [ ]:
GetDailyReturnsWithWeightsAndPortfolio(["AAPL","DAL","GLD","SBUX"],SAFEST,startDate="2018-12-31", end_date="2024-01-1")

TypeError: GetDailyReturnsWithWeightsAndPortfolio() got an unexpected keyword argument 'end_date'

In [ ]:
#each individual asset less than 30% or less
import numpy


# **Constraint for All Assets**

In [ ]:
A_BOTTOM = identity(n=4) * (-1)
A_BOTTOM

array([[-1., -0., -0., -0.],
       [-0., -1., -0., -0.],
       [-0., -0., -1., -0.],
       [-0., -0., -0., -1.]])

In [ ]:
B_BOTTOM = full(shape=[4,1], fill_value=-0.35)
B_BOTTOM

array([[-0.35],
       [-0.35],
       [-0.35],
       [-0.35]])

In [ ]:
OBJECT = rf.Portfolio(returns=EGGS, ainequality=A_BOTTOM, binequality=B_BOTTOM, sht=True)
OBJECT.upperlng = 1.5
OBJECT.assets_stats()
SAFEST = OBJECT.optimization(rm="MV" , obj="MinRisk", rf=0.15)
round(SAFEST,4)

weights
AAPL   0.2287
DAL    0.0893
GLD    0.3500
SBUX   0.3320

# **Stacking Constraints**
Constraint for all and the previous constraints

In [ ]:
a = vstack(tup=[A,A_BOTTOM])
b = vstack(tup=[B,B_BOTTOM])

In [ ]:
a

array([[-1., -1.,  0.,  0.],
       [-1., -0., -0., -0.],
       [-0., -1., -0., -0.],
       [-0., -0., -1., -0.],
       [-0., -0., -0., -1.]])

In [ ]:
b

array([[-0.6 ],
       [-0.35],
       [-0.35],
       [-0.35],
       [-0.35]])

In [ ]:
OBJECT = rf.Portfolio(returns=EGGS, ainequality=a, binequality=b, sht=True)
OBJECT.upperlng = 1.5
OBJECT.assets_stats()
SAFEST = OBJECT.optimization(rm="MV" , obj="MinRisk", rf=0.15)
round(SAFEST,4)

weights
AAPL   0.2287
DAL    0.0893
GLD    0.3500
SBUX   0.3320